BOMB_POWER = 3
BOMB_RANGE = BOMB_POWER + 1

ACTION_UP = "UP"
ACTION_RIGHT = "RIGHT"
ACTION_DOWN = "DOWN"
ACTION_LEFT = "LEFT"
ACTION_WAIT = "WAIT"
ACTION_BOMB = "BOMB"

ACTIONS = [ACTION_UP, ACTION_RIGHT, ACTION_DOWN, ACTION_LEFT, ACTION_WAIT, ACTION_BOMB]
NUM_ACTIONS = len(ACTIONS)
INVERSE_ACTIONS = {
    ACTION_UP: 0,
    ACTION_RIGHT: 1,
    ACTION_DOWN: 2,
    ACTION_LEFT: 3,
    ACTION_WAIT: 4,
    ACTION_BOMB: 5
}
MOVEMENT_INDICES = [INVERSE_ACTIONS[ACTION_UP], INVERSE_ACTIONS[ACTION_RIGHT], INVERSE_ACTIONS[ACTION_DOWN], INVERSE_ACTIONS[ACTION_LEFT]]